# Ember
foreground              #F0C080
background              #191919
selection_foreground    #1C1C1C
selection_background    #C05020
cursor                  #FF6010
cursor_text_color       #191919
active_tab_foreground     #191919
active_tab_background     #C05020
inactive_tab_foreground   #806040
inactive_tab_background   #2A2018

# black
color0      #2A2018
color8      #6A5040
# red
color1      #C03020
color9      #FF4020
# green (warm olive)
color2      #A09020
color10     #C8B420
# yellow
color3      #D08020
color11     #F0A020
# blue (muted warm)
color4      #806050
color12     #A08060
# magenta (burnt sienna)
color5      #B04030
color13     #D06050
# cyan (warm amber)
color6      #C08020
color14     #E0A030
# white
color7      #C0A080
color15     #F0D0A0
