foreground              #FFFFFF
background              #062237
selection_foreground    #062237
selection_background    #FFFFFF
cursor                  #BAA275
cursor_text_color       #101011

active_tab_foreground     #062237
active_tab_background     #40626B
inactive_tab_foreground   #40626B
inactive_tab_background   #062237

# black
color0      #294052
color8      #57778F

# red
color1      #FFEDCC
color9      #F0D8AA

# green
color2      #CCE9FF
color10     #AAD2F0

# yellow
color3      #CCF4FF
color11     #AAE1F0

# blue
color4      #9AC5E6
color12     #9AC5E6

# magenta
color5      #9AC5E6
color13     #9AC5E6

# cyan
color6      #9AD6E6
color14     #9AD6E6

# white
color7      #FFEDCC
color15     #F0D8AA
